#ifndef CRT_SHADERS_H
#define CRT_SHADERS_H

#if RETRO_PLATFORM == RETRO_PS3

static const char *crt_vshader = 
"struct out_vertex {\n"
"    float4 position : POSITION;\n"
"    float4 color    : COLOR;\n"
"    float2 texCoord : TEXCOORD0;\n"
"};\n"
"uniform float4x4 modelViewProj;\n"
"out_vertex vmain(float4 position : POSITION, float4 color : COLOR, float2 texCoord : TEXCOORD0)\n"
"{\n"
"    out_vertex OUT;\n"
"    OUT.position = mul(modelViewProj, position);\n"
"    OUT.color = color;\n"
"    OUT.texCoord = texCoord;\n"
"    return OUT;\n"
"}\n";

// Basic CRT Shader with sharp scanlines - Original foundation with improvements
static const char *crt_fshader = 
"struct out_vertex {\n"
"    float4 color    : COLOR;\n"
"    float2 texCoord : TEXCOORD0;\n"
"};\n"
"uniform sampler2D decal : TEXUNIT0;\n"
"uniform float2 texture_size;\n"
"uniform float2 video_size;\n"
"uniform float2 output_size;\n"
"uniform float  time;\n"
"uniform float  dim;\n"

"float4 fmain(in out_vertex VAR) : COLOR\n"
"{\n"
"    float2 ratio = video_size / texture_size;\n"
"    float2 ps = 1.0 / texture_size;\n"
"    float2 uv = VAR.texCoord;\n"
"    \n"
"    // Clamp UV to avoid bleeding from padding area\n"
"    float2 clamped_uv = clamp(uv, 0.5 * ps, ratio - 0.5 * ps);\n"
"    float3 res = tex2D(decal, clamped_uv).rgb;\n"
"    \n"
"    // Very sharp horizontal scanlines (Original style)\n"
"    float sc = sin(uv.y / ratio.y * video_size.y * 3.14159265);\n"
"    float scanline = lerp(1.0 - 0.7 * dim, 1.0, pow(abs(sc), 0.2));\n"
"    res *= scanline;\n"
"    \n"
"    // Simple horizontal phosphor mask (Original style)\n"
"    float mask = sin(uv.x / ratio.x * video_size.x * 3.14159265 * 2.0);\n"
"    res *= lerp(1.0 - 0.1 * dim, 1.0, abs(mask));\n"
"    \n"
"    // High brightness boost (Original: 1.35)\n"
"    res *= 1.4;\n"
"    \n"
"    return float4(saturate(res), 1.0) * VAR.color;\n"
"}\n";

// Tube TV Shader with curvature, artifacts and vignette - Original foundation with improvements
static const char *tv_fshader = 
"struct out_vertex {\n"
"    float4 color    : COLOR;\n"
"    float2 texCoord : TEXCOORD0;\n"
"};\n"
"uniform sampler2D decal : TEXUNIT0;\n"
"uniform float2 texture_size;\n"
"uniform float2 video_size;\n"
"uniform float2 output_size;\n"
"uniform float  time;\n"
"uniform float  dim;\n"

"float4 fmain(in out_vertex VAR) : COLOR\n"
"{\n"
"    float2 ratio = video_size / texture_size;\n"
"    float2 ps = 1.0 / texture_size;\n"
"    \n"
"    // Curvature calculation (Original math restored)\n"
"    float2 uv = (VAR.texCoord / ratio - 0.5) * 2.0;\n"
"    float2 uv_orig = uv;\n"
"    uv.x *= 1.0 + pow((abs(uv_orig.y) / 7.5), 2.0);\n"
"    uv.y *= 1.0 + pow((abs(uv_orig.x) / 6.5), 2.0);\n"
"    uv *= 1.01;\n"
"    \n"
"    float2 vig_uv = uv / 2.0 + 0.5;\n"
"    \n"
"    // OOB check for the tube border\n"
"    if (vig_uv.x < 0.0 || vig_uv.x > 1.0 || vig_uv.y < 0.0 || vig_uv.y > 1.0)\n"
"        return float4(0.0, 0.0, 0.0, 1.0) * VAR.color;\n"
"        \n"
"    // Vignette (Original restored)\n"
"    float vig = vig_uv.x * vig_uv.y * (1.0 - vig_uv.x) * (1.0 - vig_uv.y);\n"
"    vig = saturate(pow(max(0.00001, 16.0 * vig), 0.1));\n"
"    \n"
"    // Multi-tap Sampling with Chromatic Aberration (Fidelity improvement)\n"
"    float2 cc = vig_uv - 0.5;\n"
"    float dist = dot(cc, cc);\n"
"    float2 ca_offset = cc * dist * 0.0015;\n"
"    float3 res;\n"
"    res.r = tex2D(decal, clamp((vig_uv + ca_offset) * ratio, 0.5 * ps, ratio - 0.5 * ps)).r;\n"
"    res.g = tex2D(decal, clamp(vig_uv * ratio, 0.5 * ps, ratio - 0.5 * ps)).g;\n"
"    res.b = tex2D(decal, clamp((vig_uv - ca_offset) * ratio, 0.5 * ps, ratio - 0.5 * ps)).b;\n"
"    \n"
"    // Scanlines (Original style: centered on pixel rows)\n"
"    float scan_weight = lerp(1.0, 0.7, abs(cos(vig_uv.y * video_size.y * 3.14159265)));\n"
"    scan_weight = lerp(1.0, scan_weight, 0.6 + 0.4 * dim); // Attenuate when dimmed\n"
"    res *= scan_weight;\n"
"    \n"
"    // Frequency Artifacts (Improved flicker, rolling bars, and noise)\n"
"    float flicker = 1.0 - (0.04 * dim) * abs(sin(time * 0.15));\n"
"    \n"
"    float roll1 = frac(vig_uv.y * 0.6 + time * 0.005);\n"
"    float roll2 = frac(vig_uv.y * 0.4 - time * 0.007);\n"
"    float roll_bar = 1.0 + (0.1 * dim) * (pow(roll1, 35.0) + pow(roll2, 28.0));\n"
"    \n"
"    float noise = frac(sin(dot(vig_uv + time * 0.08, float2(12.9898, 78.233))) * 43758.5453);\n"
"    res += (noise - 0.5) * (0.035 * dim);\n"
"    \n"
"    res *= vig;\n"
"    res *= roll_bar;\n"
"    res *= flicker;\n"
"    \n"
"    // Boost brightness (Original: 1.45)\n"
"    res *= 1.5;\n"
"    \n"
"    return float4(saturate(res), 1.0) * VAR.color;\n"
"}\n";

#endif // RETRO_PLATFORM == RETRO_PS3
#endif // CRT_SHADERS_H
